# Generated by Django 5.0.6 on 2026-06-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'repartidores',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=100)),
                ('tarifa_por_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_envio', models.DateField()),
                ('repartidor', models.ForeignKey(db_column='id_repartidor', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='logistica.repartidor')),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='logistica.zona')),
            ],
            options={
                'db_table': 'envios',
            },
        ),
    ]
